# User.destroy_all
# Rating.destroy_all
# Category.destroy_all
# Survey.destroy_all
# Question.destroy_all
# Option.destroy_all
# Answer.destroy_all

User.create(username: "Reese", email: "reese@gmail.com", password: "abc123", profile_picture: "https://i.imgur.com/UwuQ4pq.jpeg", name: "Reese", location: "New York", age: 28, height: "6'1", weight: 185, gender: "Male")
User.create(username: "Michael", email: "michael@gmail.com", password: "abc123", profile_picture: "https://www.usmagazine.com/wp-content/uploads/2021/04/Michael-B-Jordan-Would-Push-Harder-During-His-Workouts-Inline-1.jpg?w=700&quality=40&strip=all", name:"Michael", location: "New York", age: 36, height: "6'1", weight: 170, gender: "Male")
User.create(username: "Taylor", email: "taylor@gmail.com", password: "abc123", profile_picture: "https://images.unsplash.com/photo-1456885284447-7dd4bb8720bf?crop=entropy&cs=srgb&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTYyMzMxNTQzNA&ixlib=rb-1.2.1&q=85", name: "Taylor", location: "New York", age: 24, height: "5'4", weight: 130, gender: "Female")
User.create(username: "Idris Elba", email: "idris@gmail.com", password: "abc123", profile_picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpnhGAe2gg7uZClR56msTLMrHH_Bvo68WuMA&usqp=CAU", name: "Idris Elba", location: "New York", age: 50, height: "6'3", weight: 190, gender: "Male")
User.create(username: "William Levy", email: "william@gmail.com", password: "abc123", profile_picture: "http://t1.gstatic.com/licensed-image?q=tbn:ANd9GcRzF9wPAbxP2EWbVjreNtU4IECgXiO83CnHfENh5hQchmwsITvzv8W3YeKd08BnatkSNQNcyZ1MdwfZOfw", name: "William Levy", location: "New York", age: 42, height: "6'0", weight: 198, gender: "Male")
User.create(username: "Kim Seok Woo", email: "rowoon@gmail.com", password: "abc123", profile_picture: "https://img.kpopmap.com/960x0/2022/02/sf9-rowoon-for-singles-korea-magazine-march-issue-1.jpg", name: "Rowoon", location: "New York", age: 26, height: "6'4", weight: 163, gender: "Male")
User.create(username: "Cardi B", email: "cardi@gmail.com", password: "abc123", profile_picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTODzKoAhxBcQ6i0vJDq0kajO2PnQRFPiBiNw&usqp=CAU", name: "Cardi B", location: "New York", age: 30, height:"5'3", weight: 118, gender: "Female")
User.create(username: "Amara La Negra", email: "amara@gmail.com", password: "abc123", profile_picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRp8YKoHLlc4iDwWq3efkaMsjnVy4M3GJnFow&usqp=CAU", name: "Amara La Negra", location: "New York", age: 32, height: "5'8", weight: 149, gender: "Female") 
User.create(username: "Zendaya", email: "zendaya@gmail.com", password: "abc123", profile_picture: "https://e0.pxfuel.com/wallpapers/837/265/desktop-wallpaper-zendaya-face-lip.jpg", name: "Zendaya", location: "New York", age: 26, height: "5'10", weight: 127, gender: "Female")
User.create(username: "Jung Ho Yeon", email: "jung-yeon@gmail.com", password: "abc123", profile_picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSka_MkhQpKoDn82nWLs7h-gjaoqOL_JyNQEg&usqp=CAU", name: "Jung Ho Yeon", location: "New York", age: 28, height: "5'9", weight: 121, gender: "Female")
User.create(username: "Lupita", email: "lupita@gmail.com", password: "abc123", profile_picture: "https://assets.mycast.io/actor_images/actor-lupita-nyong-o-53329_large.jpg?1582838473", name: "Luptia Nyong'o", location: "New York", age: 40, height: "5'5", weight: 119, gender: "Female")
User.create(username: "Adele", email: "adele@gmail.com", password: "abc123", profile_picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdqNQt_n1DGVW_D2TpDpf_pffpoCKyCOSOag&usqp=CAU", name: "Adele", location: "New York", age: 28, height: "5'9", weight: "139", gender: "Female")
User.create(username: "Rebel Wilson", email: "rebel@gmail.com", password: "abc123", profile_picture: "https://ktla.com/wp-content/uploads/sites/4/2022/11/gettyimages-1244006971-594x594-1.jpg", name: "Rebel Wilson", location: "New York", age: 43, height: "5'4", weight: "165", gender: "Female")
User.create(username: "Jack Black", email: "jack@gmail.com", password: "abc123", profile_picture:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfF31jW_OFeVJNllcy-0Tmc_G1SP3zE-QDFA&usqp=CAU", name: "Jack Black", location: "New York", age: 52, height: "5'6", weight: 209, gender: "Male",)
User.create(username: "Mark Zuckerberg", email: "mark@gmail.com", password: "abc123", profile_picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHRgW3e_YGHXR6FsZrQkjoZqCALyrUK4Q5Tw&usqp=CAU", name: "Mark Zuckerberg", location: "New York", age: 37, height: "5'7", weight: 154, gender: "Male")
User.create(username: "Daniel Radcliffe", email: "daniel@gmail.com", password: "abc123", profile_picture: "https://www.indiewire.com/wp-content/uploads/2022/11/086_Photagonist.ca_KCM_0433-e1667325258619.jpg?resize=1280,912", name: "Daniel Radcliffe", location: "New York", age: 33, height: "5'5", weight: 117, gender: "Male" )
User.create(username: "Keanu Reeves", email: "keanu@gmail.com", password: "abc123", profile_picture: "https://i.guim.co.uk/img/media/d080da48fee755dd1d201685c07694e8b3cd189c/0_356_2800_1680/master/2800.jpg?width=1200&height=900&quality=85&auto=format&fit=crop&s=65061435c8a2b5f41c6c5d46df2e1e92", name: "Keanu Reeves", location: "New York", age: 58, height: "6'1", weight: 175, gender: "Male")
User.create(username: "Amy Poehler", email: "amy@gmail.com", password: "abc123", profile_picture: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Amy_Poehler_%288894155873%29_%28cropped%29.jpg", name: "Amy Poehler", location: "New York", age: 48, height: "5'2", weight: 139, gender: "Female")
User.create(username: "Lizzo", email: "lizzo@gmail.com", password: "abc123", profile_picture: "https://static.hiphopdx.com/2021/06/210616-Lizzo.jpeg", name: "Lizzo", location: "New York", age: 34, height: "5'10", weight: 308, gender: "Female")
User.create(username: "Ariana Grande", email: "ariana@gmail.com", password: "abc123", profile_picture: "https://c4.wallpaperflare.com/wallpaper/461/841/223/ariana-grande-hd-wallpaper-preview.jpg", name: "Ariana Grande", location: "New York", age: 29, height: "5'1", weight: 106, gender: "Female")
User.create(username: "Chris Farley", email: "chris@gmail.com", password: "abc123", profile_picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIFPh0F5OgaKP5DH6vmt2heGAbGGHXamSzWA&usqp=CAU", name: "Chris Farley", location: "New York", age: 33, height: "5'8", weight: "296", gender: "Male")
User.create(username: "Dwayne Johnson", email: "dwayne@gmail.com", password: "abc123", profile_picture: "https://images.foxtv.com/static.fox35orlando.com/www.fox35orlando.com/content/uploads/2022/10/932/524/The-Rock-and-baby.jpg?ve=1&tl=1", name: "Dwayne Johnson", location: "New York", age: 50, height: "6'5", weight: 260, gender: "Male")
User.create(username: "Jack", email: "jack@gmail.com", password: "abc123", profile_picture: "https://i.imgur.io/DVAq72R_d.webp?maxwidth=640&shape=thumb&fidelity=medium", name: "Jack", age: 20, height: "5'11", weight: 170, gender: "Male")

Category.create(user_id: 1, rating_id: 1, age_range: "40 to 50", gender: "female", location: "Mississippi" )

survey1 = Survey.create(user_id: 1, description: "This survey has questions pertaining to dating preferences based solely on physical attraction")

Question.create(survey_id: 1, text: 'How important is height when it comes to attraction?')

Option.create(question_id: 1, text: 'Very Important')
Option.create(question_id: 1, text: 'Somewhat Important')
Option.create(question_id: 1, text: 'Mostly Unimportant')
Option.create(question_id: 1, text: 'Not Important')

Question.create(survey_id: 1, text: "What is your preference in hair length for what you're attracted to?")

Option.create(question_id: 2, text: 'Very Long')
Option.create(question_id: 2, text: 'Long')
Option.create(question_id: 2, text: 'Shoulder length')
Option.create(question_id: 2, text: 'Short(below shoulder length)')
Option.create(question_id: 2, text: 'Very Short')
Option.create(question_id: 2, text: "It doesn't matter/not that important")

Question.create(survey_id: 1, text: "How important is weight/fitness when it comes to attraction?")

Option.create(question_id: 3, text:'Very Important')
Option.create(question_id: 3, text:'Important')
Option.create(question_id: 3, text: 'Somewhat Important')
Option.create(question_id: 3, text: 'Somewhat unimportant')
Option.create(question_id: 3, text: 'Not Important')

Question.create(survey_id: 1, text: "What age range are you most likely to date?")

Option.create(question_id: 4, text: "18-24")
Option.create(question_id: 4, text: "25-30")
Option.create(question_id: 4, text: "30-35")
Option.create(question_id: 4, text: "35-40")
Option.create(question_id: 4, text: "40-45")
Option.create(question_id: 4, text: "45-50")
Option.create(question_id: 4, text: "50-55")
Option.create(question_id: 4, text: "55-60")
Option.create(question_id: 4, text: "60-65+")

Question.create(survey_id: 1, text: "What age range do you think women in general are the most attractive?")

Option.create(question_id: 5, text: "18-24")
Option.create(question_id: 5, text: "25-30")
Option.create(question_id: 5, text: "30-35")
Option.create(question_id: 5, text: "35-40")
Option.create(question_id: 5, text: "40-45")

Question.create(survey_id: 1, text: "What age range do you think men in general are the most attractive?")

Option.create(question_id: 6, text: "18-24")
Option.create(question_id: 6, text: "25-30")
Option.create(question_id: 6, text: "30-35")
Option.create(question_id: 6, text: "35-40")
Option.create(question_id: 6, text: "40-45")

Question.create(survey_id: 1, text: "How would you rate your physical attractiveness compared with others your age?")

Option.create(question_id: 7, text: "Much more attractive")
Option.create(question_id: 7, text: "More attractive")
Option.create(question_id: 7, text: "About the same")
Option.create(question_id: 7, text: "Less attractive")
Option.create(question_id: 7, text: "Much less attractive")

Question.create(survey_id: 1, text: "Which would matter more if you were trying to attract someone for dating? : How attractive you think your are? or how attractive others think you are?")

Option.create(question_id: 8, text: "How attractive you think your are")
Option.create(question_id: 8, text: "How attractive others think you are")

Question.create(survey_id: 1, text: "What is your age")

Option.create(question_id: 9, text: "18-24")
Option.create(question_id: 9, text: "25-30")
Option.create(question_id: 9, text: "30-35")
Option.create(question_id: 9, text: "35-40")
Option.create(question_id: 9, text: "40-45")
Option.create(question_id: 9, text: "45-50")
Option.create(question_id: 9, text: "50-55")
Option.create(question_id: 9, text: "55-60")
Option.create(question_id: 9, text: "60-65+")

Question.create(survey_id: 1, text: "What is your location?")

Option.create(question_id: 10, text: "Alabama")
Option.create(question_id: 10, text: "Alaska")
Option.create(question_id: 10, text: "Arizona")
Option.create(question_id: 10, text: "Arkansas")
Option.create(question_id: 10, text: "California")
Option.create(question_id: 10, text: "Colorado")
Option.create(question_id: 10, text: "Connecticut")
Option.create(question_id: 10, text: "Delaware")
Option.create(question_id: 10, text: "Florida")
Option.create(question_id: 10, text: "Georgia")
Option.create(question_id: 10, text: "Hawaii")
Option.create(question_id: 10, text: "Idaho")
Option.create(question_id: 10, text: "Illinois")
Option.create(question_id: 10, text: "Indiana")
Option.create(question_id: 10, text: "Iowa")
Option.create(question_id: 10, text: "Kansas")
Option.create(question_id: 10, text: "Kentucky")
Option.create(question_id: 10, text: "Louisiana")
Option.create(question_id: 10, text: "Maine")
Option.create(question_id: 10, text: "Maryland")
Option.create(question_id: 10, text: "Massachusetts")
Option.create(question_id: 10, text: "Michigan")
Option.create(question_id: 10, text: "Minnesota")
Option.create(question_id: 10, text: "Mississippi")
Option.create(question_id: 10, text: "Missouri")
Option.create(question_id: 10, text: "Montana")
Option.create(question_id: 10, text: "Nebraska")
Option.create(question_id: 10, text: "Nevada")
Option.create(question_id: 10, text: "New Hampshire")
Option.create(question_id: 10, text: "New Jersey")
Option.create(question_id: 10, text: "New Mexico")
Option.create(question_id: 10, text: "New York")
Option.create(question_id: 10, text: "North Carolina")
Option.create(question_id: 10, text: "North Dakota")
Option.create(question_id: 10, text: "Ohio")
Option.create(question_id: 10, text: "Oklahoma")
Option.create(question_id: 10, text: "Oregon")
Option.create(question_id: 10, text: "Pennsylvania")
Option.create(question_id: 10, text: "Rhode Island")
Option.create(question_id: 10, text: "South Carolina")
Option.create(question_id: 10, text: "South Dakota")
Option.create(question_id: 10, text: "Tennessee")
Option.create(question_id: 10, text: "Texas")
Option.create(question_id: 10, text: "Utah")
Option.create(question_id: 10, text: "Vermont")
Option.create(question_id: 10, text: "Virginia")
Option.create(question_id: 10, text: "Washington")
Option.create(question_id: 10, text: "West Virginia")
Option.create(question_id: 10, text: "Wisconsin")
Option.create(question_id: 10, text: "Wyoming")

Question.create(survey_id: 1, text: "What is your ethnicity?")

Option.create(question_id: 11, text: "White")
Option.create(question_id: 11, text: "Black/African American")
Option.create(question_id: 11, text: "Hispanic/Latino")
Option.create(question_id: 11, text: "Native Hawaiian or Other Pacific Islander")
Option.create(question_id: 11, text: "Native American")
Option.create(question_id: 11, text: "Asian")

Question.create(survey_id: 1, text: "What is your sexual orientation?")

Option.create(question_id: 12, text: "Straight/Heterosexual")
Option.create(question_id: 12, text: "Lesbian")
Option.create(question_id: 12, text: "Gay")
Option.create(question_id: 12, text: "Bisexual")
Option.create(question_id: 12, text: "Queer")

Question.create(survey_id: 1, text: "What is your gender?")

Option.create(question_id: 13, text: "Male")
Option.create(question_id: 13, text: "Female")
Option.create(question_id: 13, text: "Transgender")
Option.create(question_id: 13, text: "Non-binary")

Answer.create(user_id: 1, question_id: 1, text: 'Mostly Unimportant')
Answer.create(user_id: 1, question_id: 2, text: 'Long')
Answer.create(user_id: 1, question_id: 3, text: 'Important')
Answer.create(user_id: 1, question_id: 4, text: '40-45')
Answer.create(user_id: 1, question_id: 5, text: '18-24')
Answer.create(user_id: 1, question_id: 6, text: '25-30')
Answer.create(user_id: 1, question_id: 7, text: 'About the same')
Answer.create(user_id: 1, question_id: 8, text: 'How attractive others think you are')
Answer.create(user_id: 1, question_id: 9, text: '45-50')
Answer.create(user_id: 1, question_id: 10, text: 'Mississippi')
Answer.create(user_id: 1, question_id: 11, text: 'White')
Answer.create(user_id: 1, question_id: 12, text: 'Straight/Heterosexual')
Answer.create(user_id: 1, question_id: 13, text: 'Male')

